### ISSUE TITLE
🔧 [기능요청][로그인] 세종대 포털 로그인으로 가이드라인 제시필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#152]
🗒️ 설명
---
현재 화면만 봐서는 회원가입 버튼이없어서 난감하다

대양휴머니티 칼리지 비밀번호를 입력하라는 등
세종대 포털 아이디를 입력하라는등 가이드 라인을 제시해야한다

또한 서버에 비밀번호를 저장하지않아 안심해도된다는 말도 있음 좋다

관리자 페이지 참고

<img width="393" alt="image" src="https://github.com/user-attachments/assets/8eefc416-7131-4ae6-8518-0bcfda9ee164">

<img width="755" alt="image" src="https://github.com/user-attachments/assets/e6fac438-c1c5-439f-a893-cb95cc2c4683">

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh 
- 디자인: @seonglim

**Comment by thswogh** [comment]
1차적으로 수정하였습니다. 
https://test.sejong-malsami.co.kr/login
아직 디자인이 나오지 않아 마음대로 만들어봤습니다..!

**Comment by thswogh** [comment]
디자인 반영해 수정하였습니다.
[로그인 페이지](https://test.sejong-malsami.co.kr/login)

**Comment by Cassiiopeia** [comment]
@seonglim 언제나오나요?

**Comment by thswogh** [comment]
#285 해주시면 됩니다 @seonglim

**Comment by thswogh** [comment]
최종 로그인 페이지입니다

![image](https://github.com/user-attachments/assets/b55b77a8-f510-4e0d-b556-14281e035ee2)

**Comment by Cassiiopeia** [comment]
확인했습니다
