### ISSUE TITLE
🔧 [기능요청][질문글작성] 잘못된된 교과목명을 입력하였을때 잘못된 경고 표시 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#153]
🗒️ 설명
---

현재 잘못된 교과목명을 입력하더라도

Client가 문제가 있는지 파악을 할수없다

<img width="391" alt="image" src="https://github.com/user-attachments/assets/cf50655d-feb2-41bc-aad8-e271ba05f4f9">

🙋‍♂️ 담당자
---
- 백엔드: 서새찬
- 프론트엔드: 손재호
- 디자인: 김성림

**Comment by thswogh** [comment]
작성완료 누르면 팝업창으로 경고메시지 띄워서 api호출 안하게 합니다!

**Comment by Cassiiopeia** [comment]
> 작성완료 누르면 팝업창으로 경고메시지 띄워서 api호출 안하게 합니다!

어떤 경고를 띄우나요?

바로 표시하게 하는게 더 직관적이지않나요 ?

디자인팀과 협의 해봅시다

**Comment by Cassiiopeia** [comment]
현재 로직에서는 선택적으로 교과목명을 표시하려는 느낌이 좀 강한것같습니다

주소검색하고 선택하는것과같이

검색하면 결과들이 뜨고

[선택] 버튼으로 명확하게 교과목명을 선택하는 디자인 부탁드립니다

@Vhime 

![image](https://github.com/user-attachments/assets/84ee3277-33e1-4404-95d3-b643d0baf94c)
![image](https://github.com/user-attachments/assets/e154bf55-0bee-4951-9289-760185f882d5)

**Comment by Vhime** [comment]
리스트에서 과목명 누르기 전까지 확인버튼 회색으로 해서 못 누르게 하는거 ㅇㄸ

**Comment by Vhime** [comment]
<img width="677" alt="스크린샷 2024-12-01 오후 6 13 35" src="https://github.com/user-attachments/assets/c350f6dd-1a9f-41ec-9010-ccd62857cc8c">
마우스 올렸을때 청록색으로 바꿔주시면 안 되나요

**Comment by thswogh** [comment]
마우스 올렸을 때요? 모바일이면 어떻게 구분하나요??
@Vhime

**Comment by Vhime** [comment]
아 그러네 ~ 안 해도 돼여

**Comment by Vhime** [comment]
과목명 선택 전까지 확인버튼 회색으로 막아주기만 해주면 될 듯?
@thswogh

**Comment by thswogh** [comment]
과목명 선택 전에 회색(커서선택불가)으로 수정했습니다
<img width="515" alt="image" src="https://github.com/user-attachments/assets/03428fad-6ea4-451c-a382-5c9c6ccbe284" />

⬇️
<img width="515" alt="image" src="https://github.com/user-attachments/assets/91a846fb-c7ad-48f8-a31f-ef2e3a399729" />

**Comment by Cassiiopeia** [comment]
확인했습니다 이슈닫습니다
