### ISSUE TITLE
🔧 [기능요청][질문글작성] 태그 선택시 불필요한 아래 마진 및 사용자 경고, 편의성 개선 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#154]
🗒️ 설명
---

아래 마진이 좀 심한것같은데 

이외에도

초기화 버튼 이나
2개 이상 클릭 시도시 경고 Toast창 

디자인과 협의 후 개선 필요

<img width="391" alt="image" src="https://github.com/user-attachments/assets/708c67cf-d951-4e27-afbd-c5cc193bdb26">

🙋‍♂️ 담당자
---
- 백엔드: 서새찬
- 프론트엔드: 손재호
- 디자인: 김성림

**Comment by thswogh** [comment]
바텀시트의 최소 높이를 화면의 50%로 했는데, 바텀시트에 들어가는 콘텐츠 크기로 최소 높이 정하는게 나을까요?
