### ISSUE TITLE
📄 [문서] 지원하는 파일 확장자 안내 

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#155]
🗒️ 설명
---
현재 지원하는 파일 확장자 전달 드립니다

### 이미지
- JPEG, JPG, PNG, WEBP

### 문서
- PDF, DOCX, DOC, XLSX, XLS, PPTX, PPT, HWP(한글은 썸네일 미지원)

### 비디오
- MP4, AVI, MOV

### 음악
- MP3, WAV, AAC, OGG

🙋‍♂️ 담당자
---
- 백엔드: 서새찬
- 프론트엔드: 이유진, 손재호

**Comment by thswogh** [comment]
확인했습니다
