### ISSUE TITLE
🔥🔧 [긴급][랜딩] 랜딩페이지 오른쪽 상단 네비게이션 바 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#156]
🗒️ 설명
---

<img width="391" alt="image" src="https://github.com/user-attachments/assets/d80be997-6362-42cb-a31c-cbe0b5f4bc14">

홈화면을 딱 들어갔을떄 어느 화면에도 이동이 불가합니다
오른쪽 위 사람이모지는 로그인 페이지로 연결됩니다

빠른 기능 추가 부탁드립니다

<img width="302" alt="image" src="https://github.com/user-attachments/assets/8528de66-11dc-4962-b643-49bdeccc9b04">

기본적인 기능이라 최대한 빨리 부탁드립니다

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh
- 디자인: 윤지희

**Comment by Cassiiopeia** [comment]
<img width="1084" alt="image@Cassiiopeia  src="https://github.com/user-attachments/assets/169c4cf3-57bd-43cc-bd40-177e49328544">


@newjinlee 

피그마에 최종 햄버거 버튼 완료했습니다 확인부탁드립니다

**Comment by newjinlee** [comment]
완료했습니다.
