### ISSUE TITLE
🔧 [기능요청][자료] 자료반환시 썸네일 이미지 URL 좌표 변수이름 수정 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#159]
🗒️ 설명
---
![image](https://github.com/user-attachments/assets/2fa5f3bb-3f50-466f-9cb8-efb76ce8bea8)

질문게시글 QuestionPost
자료게시글 DocumentPost 

을 서버에서 다루고 있는데

QuestionPost에서 썸네일 URL 변수이름이 thumbnailUrl입니다

그래서 자료게시판에서도

자료당 썸네일 반환시 썸네일 URL변수를 다음과 같이 통일시킵니다

⚙️ 작업 내용
---
DocumentPost (자료게시글) 에서

썸네일 URL 변수이름 수정사항

    previewUrl -> thumbnailUrl 

확인후 변경 부탁드립니다

🙋‍♂️ 담당자
---
- 백엔드: 서새찬 @Cassiiopeia 
- 프론트엔드: 손재호 @thswogh , 이유진 @newjinlee

**Comment by thswogh** [comment]
확인했습니다
