### ISSUE TITLE
🔥❗ [긴급][버그][질문상세] 댓글 등록 버튼 연타시 다중 댓글 작성되는 문제

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#175]
🗒️ 설명
---
- 현재 질문상세에서 댓글을 남길떄 연타를 하게되면 2,3개씩 댓글이 작성합니다
- fetch할때 버튼을 비활성화 시켜야할것같아요. 수정 부탁드립니다
- 
![image](https://github.com/user-attachments/assets/c0484d45-77ea-4221-958c-a1af049726cf)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
#240 
수정했습니다!
