### ISSUE TITLE
🎨🔧 [디자인][긴급][기능요청][질문메인] 메인 리스트에 교과목명 표시 필요 및 통일성 개선 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#176]
🗒️ 설명
---
- 현재 질문 메인 페이지에 태그와 교과목명을 표시하고있는데요
- 사용자가 사용할때 태그 엽전현상금도 보겠지만 교과목명 무조건적으로 먼저 봐야될것같습니다
- 해당부분 개선된 UI가 필요해 보입니다. 질문메인페이지에 각 질문들에 교과목명을 표시해주세요

아래사진은 밖에서는 아무런 태그적인 요소가 없지만

게시글을 들어가면 교과목명과 엽전현상금이 0 인 정보가 뜨고
아래에 회색으로 태그가 뜹니다

엽전현상금이 0이면 넣을필요가없어보이구요

결론적으로는 통일성이 부족하다 입니다

제가 생각하는건

질문 상세페이지처럼 질문 메인페이지에서 질문 카드에

교과목명, 엽전현상금을 색깔로 표시해야할것같습니다

![image](https://github.com/user-attachments/assets/16c7bb15-d687-43c1-8994-c730c1cd924c)

![image](https://github.com/user-attachments/assets/51c61edb-80f2-4595-8c8f-e44705692189)

둘다 같은글에 대한 

카드와 상세 페이지인데요 한번 보시고 확인 부탁드립니다

정적태그, 커스텀 태그가 포함된 게시글도 함께 공유해드립니다

![image](https://github.com/user-attachments/assets/5a96723f-7ffc-4c8c-ac6d-ae8a27801247)
![image](https://github.com/user-attachments/assets/0e01df72-5d17-4a02-921d-7c04926fdcbe)

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee 
- 디자인: @Vhime

**Comment by thswogh** [comment]
확인했습니다. 디자이너분들 교과목명 태그 디자인 부탁드립니다!

**Comment by Vhime** [comment]
제가 그래서요 아니 이거 회의에서 계속 말할려했는데 태그 하나만 하면 안 되나???요???
자리가 없어요 ㄹㅇ 
<img width="442" alt="스크린샷 2024-12-01 오후 5 48 43" src="https://github.com/user-attachments/assets/c53d2856-1d89-4ea5-9572-19da878e0500">

**Comment by Cassiiopeia** [comment]
@thswogh 확인 부탁드립니다

**Comment by thswogh** [comment]
이건 다같이 정해야할 거 같은데, 자리가 없긴한데 태그를 교과목명 옆(오른쪽)에 두는건 별로인가요?

**Comment by Vhime** [comment]
일단 해봄여

**Comment by Cassiiopeia** [comment]
@Vhime  완료되면 여기나 카톡에 공유 부탁드립니다

**Comment by thswogh** [comment]
카드에 들어가는 정보가 너무 많고 위치가 애매해서 정적태그 제거했습니다

<img width="358" alt="image" src="https://github.com/user-attachments/assets/4c4201e5-eae3-43fe-a94d-276219f6843c">

**Comment by Cassiiopeia** [comment]
@Vhime 예진님 확인해보시고 문제가 있거나 수정이 필요한것 것같으면 다시 이슈 reopen 해주시면될것같습니다

해당사항 요구사항에 맞게 구현완료되었으므로 이슈 닫습니다
