### ISSUE TITLE
❗ [버그][QA] 프론트 버그 수정 필요

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#177]
🗒️ 설명
---
<로그인>
- [x] 로그아웃 시 "로그아웃 되었습니다. 다시 로그인해주세요." Alert 창 -> "로그아웃에 실패했습니다. 다시 시도해주세요." Alert 창
![스크린샷 2024-11-27 오전 11 28 47](https://github.com/user-attachments/assets/46b05319-5063-4a58-9804-c868222cd539)

<랜딩페이지>
- [ ] 자료글은 엽전 현상금이 존재하지 않기에 다른 카드 디자인이 필요해보임 
![스크린샷 2024-11-27 오후 2 24 18](https://github.com/user-attachments/assets/ab916e6f-a887-4fb9-bbc6-a2344bff8597)

<질문게시판>
- [ ] 질문글 작성 시 정적태그 바텀시트 사이즈가 너무 큰 느낌? (태그 사이즈에 비해 여백이 너무 많이 남는 것 같아여) 
![스크린샷 2024-11-27 오후 2 30 17](https://github.com/user-attachments/assets/f82aef09-9b10-44f5-b421-9c0b1526e33f)

- [ ] 내가 쓴 글 좋아요 누르는 경우 "본인이 작성한 글에는 좋아요를 누를 수 없습니다." 등의 Alert창 뜨는거 어케생각하시나요?? 

- [x] 댓글 작성 시 연속클릭하면 댓글이 여러개 작성되는 오류

- [x] 필터링 선택해서 글 열람한 뒤 뒤로가기 버튼 누르면 필터링이 초기화됨(버그는 아닌데 논의해봐야할 것 같아요)

- [ ] 필터링 바텀시트에서 X 표시와 체크 버튼이 겹치는 버그
![스크린샷 2024-11-27 오후 2 37 16](https://github.com/user-attachments/assets/bdfe2e43-5d63-47a5-8bc5-d6d02958a5d0)

- [ ] 필터링 후 글 개수가 적어 단일 페이지인 경우 페이지네이션 '이전버튼', '다음버튼' 색상이 다름
![스크린샷 2024-11-27 오후 2 39 02](https://github.com/user-attachments/assets/5b215699-4b2d-4557-bedd-741fcc09cf52)

- [ ] 필터링에서 엽전 현상금 순으로 정렬할 경우 "서버에 문제가 발생했습니다." Alert 창 발생 (백 로직 확인해보겠습니다) 

- [x] 답변 채택 후 '채택됨' 파란 태그(?) 버튼(?) 클릭시 파란 색상이 사라지는 버그 + 파란색이 사라진 뒤 다른 화면 클릭시 다시 원상복구 
![스크린샷 2024-11-27 오후 2 46 19](https://github.com/user-attachments/assets/244bea3b-bff1-4382-9385-3c01ac275c7b)

- [x] 답변 작성 시 글자수 일시적으로 넘어가는 버그 + 글자수 2001자로 답변 등록 버튼 누르면 Alert창이 두개가 뜸 (서버오류Alert -> 답변 등록 중 오류발생Alert), 서버 오류 Alert창은 웬만하면 사용안하시는게 좋습니다 
![스크린샷 2024-11-27 오후 2 50 09](https://github.com/user-attachments/assets/c2c75e0b-ee47-4049-a173-77c25f4c310f)

- [ ] 질문 게시판 글 작성시 본문 2000자 입력 후 글 등록 시 오류 발생

- [ ] 커스텀 태그 길이 10자 작성시 줄바꿈 문제 
![스크린샷 2024-11-27 오후 3 08 38](https://github.com/user-attachments/assets/07a84e8b-dddc-4e4a-a5de-1615c5bb295f)

- [ ] 필터링 된 글이 존재하지 않는 경우 하단 페이지네이션 버튼 여부 및 "글이 존재하지 않습니다" 와 같은 문구 출력에 대해 논의가 필요해 보입니다
![스크린샷 2024-11-27 오후 3 09 27](https://github.com/user-attachments/assets/a70718c4-971e-4cb2-9f08-6e79753647f4)

- [ ] 질문 게시판 글 작성 화면에서 파일 첨부할 때 동일한 파일 중복 첨부시 Alert창이 뜨면 어떨까요? 현재는 아무 문구 없이 자동으로 첨부가 안됩니다 

- [x] 사진 추가해서 글 등록시 글 상세보기에서 해당 사진이 보이지 않습니다 (썸네일은 잘 보입니다) 
![스크린샷 2024-11-27 오후 3 14 25](https://github.com/user-attachments/assets/baee3373-334b-4511-ad8c-d86b53126377)
![스크린샷 2024-11-27 오후 3 14 33](https://github.com/user-attachments/assets/f502355b-3199-4425-95dc-d3c8574efbd7)

- [x] 글 등록시에도 버튼 연타하는 경우 여러개의 글 등록되는 버그 

- [x] 뒤로가기 버튼 클릭시 이전 화면이 아닌 상위 페이지로 이동 필요

- [ ] 질문글 상세페이지에서 사진 클릭 후 좌우 스와이프 시 뒷 배경이 움직이는 버그 (+ 사진이 여러장 등록된 경우 자세히보기 페이지에서도 좌우 스와이프 가능하게 할 수 있을까요?)
https://github.com/user-attachments/assets/eea752e6-2967-4741-8e7c-376d9e1f2421

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: 이유진, 손재호
- 디자인:

**Comment by Cassiiopeia** [comment]
@Chuseok22 이거 지금 안고쳐진 부분들은 분리해서 잘 적어서 올려주세요

어떤식으로 되면 좋을것같다 등등
디자인이 나와야될것같다 등등
다른글 참고하셔서 정리해서올려주세요 한번에 다 올려버리면 읽기 어렵네요....

정리해서 각각 이슈 올려주시면될것같습니다

**Comment by newjinlee** [comment]
@Chuseok22 질문글 상세페이지에서 사진 클릭 후 좌우 스와이프 시 뒷 배경이 움직이는 버그 (+ 사진이 여러장 등록된 경우 자세히보기 페이지에서도 좌우 스와이프 가능하게 할 수 있을까요?)
>> 어렵습니다 ..................................................................................

**Comment by Cassiiopeia** [comment]
해당부분 각각 이슈를 작성하여 이슈 닫습니다
