### ISSUE TITLE
❗ [버그][랜딩] 모바일 환경에서의 버그 수정 필요

### ISSUE THREAD

**Issue by minhong620** [Sejong-Balsamic/Malsami-FE#184]
🗒️ 설명
---
- 모바일 환경(아이폰13, 사파리)에서 일어나는 버그들입니다.
- [x] 로그인 직후에 화면이 확대됩니다.
![KakaoTalk_20241128_000543453](https://github.com/user-attachments/assets/ef5e94a3-7fcc-4c83-856a-1891bd81f070)

- [x] 가장 하단으로 가는 버튼을 누르면 가장 하단으로 가지 않습니다. (캡쳐한 곳까지 내려갑니다.)
![KakaoTalk_20241128_000543453_01](https://github.com/user-attachments/assets/590b4126-7e0c-4e08-9393-9b1c7ac3b56b)

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
일부러 HOT 인기자료까지 내린겁니다!!

**Comment by newjinlee** [comment]
iOS/Safari에서는 글씨크기가 16px 미만일 때 사용자의 편의를 위해 auto zoom-in을 해주는 기능이 있다고 합니다.
이를 막기 위해 <meta> 태그를 수정했습니다. 
```
<meta
    name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
/>
```
이제 페이지 전체에서 줌을 할 수 없습니다. 덕분에 <input>에서의 자동 줌도 막을 수 있게 되었습니다 ~ ㅎ
