### ISSUE TITLE
🔧 [기능요청][랜딩] 화면이동 플로팅 버튼

### ISSUE THREAD

**Issue by jihee127** [Sejong-Balsamic/Malsami-FE#212]
🗒️ 설명
- 랜딩 페이지 맨 아래로 내려갔을 때 화면이동 플로팅 버튼이 사라지게 해주세요.

![image](https://github.com/user-attachments/assets/e5b76ca2-7e2f-4b98-9899-3172219e01f6)

- 참고자료: https://42library.kr/information
  여기는 위로 올라가는 플로팅 버튼인데 페이지 맨 위로 가면 플로팅 버튼이 사라집니다.

![image](https://github.com/user-attachments/assets/5394029b-7f45-46dc-86c6-69fb26b71eee) ![image](https://github.com/user-attachments/assets/b3e14724-655e-4bf5-a048-79954635d57d)

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee 
- 디자인: @jihee127

**Comment by newjinlee** [comment]
#243 
수정했습니다!
![image](https://github.com/user-attachments/assets/650e2dc8-da5c-46c2-be38-24fcb67c18e1)

**Comment by Cassiiopeia** [comment]
부드럽게 애니메이션 추가해주세요

**Comment by newjinlee** [comment]
새 이슈 올리셔서 내립니다 ~
