### ISSUE TITLE
🔧 [기능요청][마이페이지] 레벨 생성에 따른 마이페이지 수정 요청

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-FE#213]
🗒️ 설명
---
- 경험치 레벨 도입에 따라 마이페이지 카드 디자인 수정이 필요합니다.
- 현재 디자인
![image](https://github.com/user-attachments/assets/1cfe9d9c-e741-454d-9306-f953248e4f01)

⚙️ 작업 내용
---
- 필요한 디자인
- [ ] 2가지 색의 숫자 아이콘(1 ~ 9) - 종9품 ~ 정1품 레벨 명시를 위해 필요
- [ ] progress bar 레이아웃 - progress bar 하단의 bar 설명 부분에 레벨 표시 + 다음 레벨 표시
- [ ] 카드 반대편 디자인 - 그래프로 경험치 백분위를 보여주는 것이 의미가 없어졌고 카드 앞면의 정보와 겹침. 레벨에 대한 설명 카드로 변경. 종9품 ~ 정1품 아이콘 나열하고 각각 짧게 설명이 있으면 좋겠습니다.. (개인적인생각임)
![image](https://github.com/user-attachments/assets/73e45dfc-7f02-481b-95f5-e1318ee728de)
(참고안되는참고자료)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee 
- 디자인: @jihee127

**Comment by Cassiiopeia** [comment]
확인했습니다

**Comment by jihee127** [comment]
확인했습니다~
