### ISSUE TITLE
🎨⚙️ [디자인][기능추가][마이페이지] 마이페이지 수정 및 개선 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#216]
🗒️ 설명
---
- [ ] : 게시판별 분류 (작성글 개수) 중복됨
- [ ] : 경험치 UI 수정 필요
- [ ] : 카드 뒷면 뭐 넣을지 제시필요

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee 
- 디자인: @jihee127

**Comment by newjinlee** [comment]
이슈가 겹칩니다 #213
