### ISSUE TITLE
❗ [버그][랜딩] 햄버거바 세로에 흰색줄 수정부탁드립니다

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#221]
🗒️ 설명
---

저 뒤에 회색부분처리한것과 햄버거바 사이에 흰색줄이 있어요

<img width="154" alt="image" src="https://github.com/user-attachments/assets/c4ab4390-e57b-412d-b822-193420ac40ec">

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
수정했습니다!

**Comment by newjinlee** [comment]
![image](https://github.com/user-attachments/assets/5c1c8870-0375-4566-a03b-9595ab0380d1)
