### ISSUE TITLE
🎨🔥❗[디자인][긴급][버그][질문페이지] 상단 UI 수정 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#222]
🗒️ 설명
---
- 지금 디자인 일관성이 없습니다. 
- 디자인단부터 수정부탁드립니다

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/1e7434f4-2163-4d51-8625-7253d2f1efac">

🙋‍♂️ 담당자
---
- 프론트엔드: 전부
- 디자인: 지희뺴고 전부

**Comment by newjinlee** [comment]
수정했습니다!

**Comment by newjinlee** [comment]
![image](https://github.com/user-attachments/assets/f162c9eb-59d5-4b07-9442-841335644470)
![image](https://github.com/user-attachments/assets/dc0afedc-5d4f-4942-9bf1-1f576e1995dc)

**Comment by newjinlee** [comment]
달라보이지만 암튼 같음
