### ISSUE TITLE
🎨 🔧 [디자인][기능요청][채택] 채택하기 모달창 UI 개선 필요 

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#224]
🗒️ 설명
---
- 모달창이 너무 모던해서. 살짝 조선시대향이나 이모디콘 부탁드립니다

<img width="392" alt="image" src="https://github.com/user-attachments/assets/6b8bf0d5-ab57-4db0-b7cc-4bb69a0efa22">

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee 
- 디자인: @seonglim @jihee127

**Comment by seonglim** [comment]
확인했습니다

**Comment by newjinlee** [comment]
@jihee127 담당자가 변경되었습니다! 확인 부탁합니다

**Comment by Cassiiopeia** [comment]
해당 모달에 대해서 제목이 필요없는 모달이 있는것같습니다

어떻게 표시를 할지 변경 부탁드립니다

아님 모달창에 대한 전체적인 디자인을 수정해주셔도될것같습니다

**Comment by newjinlee** [comment]
마이페이지 내의 모달창도 수정이 필요합니다.
제목이 필요한 곳과 필요하지 않은 곳을 구별해주시면 좋을 것 같습니다!
![image](https://github.com/user-attachments/assets/f3ddd331-9dca-40a4-ae6a-35b2d753e1b6)
