### ISSUE TITLE
🎨🔧 [디자인][기능요청][로그인] 로그인 페이지 요청

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#225]
🗒️ 설명
---
- 손을 흔드는것?
- 뒤에배경?
- 안녕하시오! 와 그림과 간격이 멀다?
- 팔을 만들어야함

<img width="423" alt="image" src="https://github.com/user-attachments/assets/7560e887-2ce0-4ef4-b388-566a0e7ef34a">

<img width="387" alt="image" src="https://github.com/user-attachments/assets/52bfbe93-e68e-477a-86b6-06aa5b0e78ed">

<img width="397" alt="image" src="https://github.com/user-attachments/assets/7f255eb4-545e-4fe9-a373-cf1a4ef7961f">

<img width="307" alt="image" src="https://github.com/user-attachments/assets/b59fb8e2-4f02-495d-a04e-32388050ebd0">

🙋‍♂️ 담당자
---
- 디자인: @seonglim

**Comment by seonglim** [comment]
확인했습니다!

**Comment by newjinlee** [comment]
이슈 닫겠습니다 ~
![image](https://github.com/user-attachments/assets/14fa9ac5-ce4b-45fb-a83d-bf244873e82a)
