### ISSUE TITLE
🎨🔧 [디자인][기능추가][질문메인] 질문메인페이지 필터링 로직과 UI 개선 요청

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#228]
🗒️ 설명
---

# 요구사항
- [x] 이거 필터링 적용한것을 리스트화면에서 볼수있어야한다 ( 밖에서 내가 어떤 필터링을 했는지 볼수있어야함 )
- [ ]  초기화 버튼 UI
- [x]  메뉴버튼이 작아요

<img width="460" alt="image" src="https://github.com/user-attachments/assets/332fe5f3-8fea-4f2a-b484-25d437341700">

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by newjinlee** [comment]
확인했습니다!

**Comment by thswogh** [comment]
@Vhime 초기화버튼 디자인 부탁드립니다

**Comment by Vhime** [comment]
ㅜㅜㅠㅠㅠ
