### ISSUE TITLE
⚙️ [기능추가][마이페이지] 점수 숫자 올라가거나 변화하는 애니메이션 개선필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#229]
🗒️ 설명
---
- T맵에서 카라이프를 눌렀을때 숫자가 변화하면서 운전점수 ??점이 뜨는데 이떄 애니메이션으로 숫자가 움직이면서 표시되게해주세요
- 언제나 부드럽게~

<img width="388" alt="image" src="https://github.com/user-attachments/assets/3b01fcca-1530-496c-aad3-3ca1cae3657e">

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
적용했습니다 확인해주세요!

https://github.com/user-attachments/assets/2eb8df10-3ce7-45d2-8f7d-416b5ed85042

**Comment by Cassiiopeia** [comment]
@jihee127 확인부탁드립니다 
제생각 넘빠른것같지않아요? 
그 빨라지다가 느려지는 그럼 고오오급스러웠음 좋겠는데 말이죠

**Comment by jihee127** [comment]
@Cassiiopeia 조오금 빠른 거 같기도 하고요...?

**Comment by Cassiiopeia** [comment]
@newjinlee @jihee127  이게 랜덤값이 아니라 0부터 올라가더라구요

그래서 하나가 98이고 하나가4면

98은 엄청 빨리올라가고 4는 천천히 올라가서 같은 시간에 끝나요

랜덤값으로 보이다가 같이 값이 보이는건 안되나요?

**Comment by Cassiiopeia** [comment]
해당기능구현 완료로 이슈 닫습니다. 고생하셨습니다
