### ISSUE TITLE
⚙️ [기능추가][자료작성] 자료작성시 alert 창 말고 toast창, 대기시간동안 모달창 표시 기능 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#230]
🗒️ 설명
---
- 이거 toast 창으로 성공적으로 올렸습니다. 뜨게해주세요
- 근데 파일 용량이 크면 로딩 올리는중입니다 뜨게 해주세요
그리고 이미지표시해주고 loading spinner 있으면 좋을것같습니다. 일단 디자인 은 나중에부탁하고 스피너바 넣는방식으로 나중에 언급해서 확인받고 수정해봅시다
- 성공적으로 로딩하면 당연히 자료메인으로 바로가게 

<img width="583" alt="image" src="https://github.com/user-attachments/assets/90aee6f8-ad0f-454b-8ed4-48ed3e8ef5ee">

#### alert창 toast창으로 교체, 작성완료 후 응답 올 때 까지 loadingSpinner 구현하기
- [x] 자료 글등록
- [x] 질문 글등록
- [x] 자료 답변게시판 글등록
- [ ] 자료 요청

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh 
- 디자인: @seonglim

**Comment by thswogh** [comment]
확인했습니다

**Comment by Cassiiopeia** [comment]
@thswogh @newjinlee  이거 어느정도 전부 수정된건가요??

**Comment by thswogh** [comment]
@Cassiiopeia 자료 등록 시, alert창 대신 toast가 나오게 수정했습니다.
사진이나 영상이 올라가면 loadingSpinner를 띄우자고 하셨는데 자료가 올라가기까지의 시간을 프론트에서 확인할 수 있을까요?
자료를 올리면 무조건 일정시간 이상 loadingSpinner를 띄워야할까요?

**Comment by thswogh** [comment]
api 호출 요청을 한 뒤 응답이 반환되기까지 로딩창 나오게 구현하는 방식이 맞는 것 같습니다.
시간소요 확인 로직은 만들 필요가 없을 것 같습니다.

위 로직과 같이 글 등록 시, 글등록 성공 혹은 실패 응답 전까지 로딩창 나오게 구현했습니다.

**Comment by Cassiiopeia** [comment]
@thswogh 
글을 등록하는 부분에서 미디어를 추가하는 부분은 다음과 같습니다
글등록시, 답변등록시

현재 상황은 다음과 같습니다

### 글 등록 (질문, 자료, 공지사항, 질문요청) 
- 질문등록: 정상 동작
- 자료등록: 정상 동작
- 공지사항: 해당 기능 미구현
- 질문요청: 해당 기능 미구현

### 답변 등록 (질문)
- 질문답변 등록: 비정상 동작


확인부탁드립니다

**Comment by thswogh** [comment]
@Cassiiopeia 
- `질문등록, 자료등록`만 수정한 것 맞습니다

- `공지사항 글등록`  
디자인 요청하겠습니다
공지사항 글은 관리자페이지서 써야 맞는 거 아닐까요?

- `자료요청 글등록`  디자인 요청하겠습니다

- `질문 답변 등록`은 유진누나 담당이라 새로 assign하겠습니다!

**Comment by Cassiiopeia** [comment]
> @Cassiiopeia
> 
> * `질문등록, 자료등록`만 수정한 것 맞습니다
> * `공지사항 글등록`
>   디자인 요청하겠습니다
>   공지사항 글은 관리자페이지서 써야 맞는 거 아닐까요?
> * `자료요청 글등록`  디자인 요청하겠습니다
> * `질문 답변 등록` 수정하겠습니다~

@thswogh 네네 공지사항작성은 백엔드에서 처리할 예정이기때문에

공지사항은 글 등록은 고려할 필요없을것같습니다

질문 답변 등록 수정부탁드립니다

**Comment by newjinlee** [comment]
자료요청 디자인 이슈 따로 올리서 해당 이슈 닫겠습니다
