### ISSUE TITLE
🔥 🎨[긴급][디자인][자료메인] 아이콘들 두루마리 없는 버전 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#231]
🗒️ 설명
---
- 두루마리없는 버전 급하게 요청합니다

<img width="391" alt="image" src="https://github.com/user-attachments/assets/8607055d-7a36-4153-8bc4-241ebe1a6e0c">

🙋‍♂️ 담당자
---
- 프론트: @thswogh 
- 디자인: @seonglim

**Comment by seonglim** [comment]
확인했습니다!

**Comment by Cassiiopeia** [comment]
@seonglim 완료하시면 오른쪽에 label에 확인대기 변경 부탁드려요~

**Comment by newjinlee** [comment]
![image](https://github.com/user-attachments/assets/29d20f5c-fa70-440a-af65-77b2021a0ca6)
