### ISSUE TITLE
🔥 ❗[버그][긴급][질문메인] "학부선택"이 초기화되는 문제 

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#232]
🗒️ 설명
---
- 질문상세에 들어가서 나왔을때 내가 선택한 "학부선택" 필터가 초기화 되고있습니다
- 이부분이 유지되어야합니다

- 필터부분도 유지되어야할것같습니다.

<img width="391" alt="image" src="https://github.com/user-attachments/assets/ba4aa8e7-e397-43bf-8ffc-9b7d72a04dab">

<img width="393" alt="image" src="https://github.com/user-attachments/assets/f35c6bcf-c5cc-4910-9f7d-0ee5012adb93">

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by thswogh** [comment]
<img width="371" alt="image" src="https://github.com/user-attachments/assets/e571bc86-8927-4127-827f-90a4936febbd">
필터부분, 학부선택 초기화 되는 문제 해결하였습니다

**Comment by Cassiiopeia** [comment]
확인했습니다 고생하셨습니다

이슈 폐쇄합니다
