### ISSUE TITLE
🎨 ⚙️ [디자인][기능추가][질문상세] 질문상세페이지 댓글 페이지네이션 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#233]
🗒️ 설명
---
- 질문 상세보기에서 댓글 페이지네이션 있어야될것같습니다 

"더보기 버튼"이 추가되어야할것같습니다
- 디자인 요청 부탁드립니다

<img width="389" alt="image" src="https://github.com/user-attachments/assets/9d77e882-4c18-44eb-8ab2-653ed9e6811e">

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: @newjinlee 
- 디자인: @seonglim

**Comment by seonglim** [comment]
확인했습니다

**Comment by thswogh** [comment]
@newjinlee 
페이지네이션 UI구현했는데 
app > board > question > page.tsx 참고해서 구현하시면 됩니다~

**Comment by newjinlee** [comment]
@thswogh  감사하오
