### ISSUE TITLE
🎨 [디자인][기능추가] 질문게시판 메인 필터링바 디자인 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-FE#234]
🗒️ 설명
필터링 바에서 필터 선택 시, `태그선택`만 필터링바에 나타나는데
추가적으로 `채택여부`와 `정렬`이 필터링바에 나타나야 합니다.

`채택여부`와 `정렬` 부분 디자인 부탁드립니다
<img width="629" alt="image" src="https://github.com/user-attachments/assets/738a1df7-2f5c-442c-b698-e70738e098be">

🙋‍♂️ 담당자
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by thswogh** [comment]
<img width="369" alt="image" src="https://github.com/user-attachments/assets/21e3d942-2256-4dbb-b88b-ad18d0c4151b">
`정렬` 부분만 색깔 디자인 부탁드립니다

**Comment by Cassiiopeia** [comment]
여기 있었군요 좋습니다

**Comment by Vhime** [comment]
그 컬파에 두번째로 연한 청록색 ㅇㄸ

<img width="681" alt="스크린샷 2024-12-01 오후 6 07 58" src="https://github.com/user-attachments/assets/de59cd12-3562-42b7-bea7-e94236dd86b7">

**Comment by thswogh** [comment]
좋습니다~
<img width="374" alt="image" src="https://github.com/user-attachments/assets/d0afcaf3-b0e1-4a5b-9b7d-fa94987ceb29">

**Comment by Vhime** [comment]
<img width="241" alt="스크린샷 2024-12-02 오전 1 23 45" src="https://github.com/user-attachments/assets/e510fefa-f4fa-4b18-9144-e2779bce7cfc">

재호형 ~~~~~ 봐주세요 ~~~~~
@thswogh

**Comment by thswogh** [comment]
확인ㅜㅜ

**Comment by thswogh** [comment]
![image](https://github.com/user-attachments/assets/f4d0030d-d501-433f-a38f-c776bd4593f7)
@Cassiiopeia @Vhime 확인하시고 피드백이나 이슈 닫아주세요

**Comment by Cassiiopeia** [comment]
@thswogh 

현재 X를 클릭해서 적용된 태그를 지울떄
전체 페이지 리로드가 발생합니다

이는 리액트 컴포넌트가 추구하는 방식이 아니며
 api 요청에 부하를 줄수있습니다
 
 태그를 수정하였을때 
 https://api.sejong-malsami.co.kr/api/question/filter
해당 API 만 호출하고 
아래 리스트 컴포넌트와 태그가 사라지는 부분만 랜더링되게 수정 부탁드립니다

<img width="392" alt="image" src="https://github.com/user-attachments/assets/d1e53ba4-c20b-4e0b-979c-707505a435e4">

**Comment by thswogh** [comment]
``` javascript
 const getQuestionDatas = async () => {
  const params = {
    ...
  };
  try {
    const unansweredData = await getUnansweredQNAs({ faculty });
    const categoryData = await getCategoryQNAs(params);
  }
};
```
기존 코드에서는 비답변부분, 필터링 부분을 동시에 호출 했는데, api호출하는 부분을 2개로 나누었습니다.

``` javascript
 const getUnansweredDatas = async () => {}
   const getCategoryDatas = async () => {}
```

**Comment by Cassiiopeia** [comment]
확인되었습니다 ~
