### ISSUE TITLE
🎨 ⚙️[디자인][기능추가][에러] 에러페이지 404 UI 개선 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#235]
🗒️ 설명
---
- 404 페이지 화면을 좀 멋스럽게 바꿔주세요 개발중입니다 등등 
- 홈화면으로 연결시키는 버튼 필요할것같습니다
- 디자인이 한번 확인해주세요. 살짝 아쉬워하는 사람의 일러스트 있으면 좋을것같습니다

- 아래는 예시입니다

<img width="390" alt="image" src="https://github.com/user-attachments/assets/319326ca-2b8b-4bfc-a449-425fb1c853b9">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/62141dee-fb3f-4798-b402-25e3e9e78a70">

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee 
- 디자인: @seonglim

**Comment by seonglim** [comment]
확인했습니다!

**Comment by newjinlee** [comment]
중복 이슈로 폐쇄합니다 #284
