### ISSUE TITLE
🚀 [기능개선][로딩] 페이지 로딩 관리

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-FE#250]
🗒️ 설명
---
-페이지 로딩 시 시간이 걸리는 부분에 스피너를 추가했는데, 전역에서 로딩 상태를 관리하는게 일반적이라네요 ..
그러면 모든 데이터 fetch 또는 비동기 작업 중에 스피너를 표시할 수 있습니다. 
급하지 않으니 리팩토링 때 진행해봅시다 ...

⚙️ 작업 내용
---
1. 전역 로딩 상태 관리:
React Context 또는 상태 관리 라이브러리 (예: Redux)로 전역 isLoading 상태를 추가합니다.
2. 스피너 컴포넌트 작성 (되어 있음)
3. 사용

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee

**Comment by thswogh** [comment]
확인했습니다~

**Comment by newjinlee** [comment]
로딩 관리 형식이 바뀌어 이슈 닫습니다
