### ISSUE TITLE
❗ [버그][햄버거바] 로그인하지않았을시 햄버거바에서 이용도우미, 공지사항 mapping 개선과 뒤로가기 오류 

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#259]
🗒️ 설명
---
- 지금 로그인하지않고 이용도우미, 공지사항 이동하였을때 개발중인 창이 뜨는데 mypage/notice 이런 주소로 되어있어서 뒤로가기를 눌렀을때 
- mypage로 못들어가고 스피너바만 계속 돕니다
- 마이페이지는 인증이 필요한 창이므로 마이페이지로 들어갔을때는 로그인페이지로 이동해야하는 로직이 필요해보이는데요

- 애초에 햄버거바에서 이용도우미 공지사항을 들어갈수있는것이라면 mypage/notice 같은 url 주소가 잘못된것같습니다
- 적절한 방법을 고민하여 수정 부탁드립니다

![image](https://github.com/user-attachments/assets/9da3b2d6-3de4-40c2-8aee-4a474af507be)

![image](https://github.com/user-attachments/assets/95c80ba6-3e48-4a04-943b-32b0deb585f9)

![image](https://github.com/user-attachments/assets/7f2d271d-e760-466c-93b3-d6d88c448826)

🙋‍♂️ 담당자
---
- 백엔드: 이름
- 프론트엔드: 이름
- 디자인: 이름

**Comment by newjinlee** [comment]
확인했습니다! 관련 페이지는 마이페이지 밖으로 빼야겠네여

**Comment by Cassiiopeia** [comment]
기존에있던 마이페이지 페이지들도 잘 연결되게 수정부탁드립니다. 뒤로가면 흰색화면떠요

**Comment by newjinlee** [comment]
!! 수정했습니다 확인해주세요
