### ISSUE TITLE
❗ [버그][랜딩] 로그인 안 해도 랜딩에 이름 뜨는 버그

### ISSUE THREAD

**Issue by jihee127** [Sejong-Balsamic/Malsami-FE#265]
🗒️ 설명
---
- 로그인을 아직 안 했는데 랜딩페이지 메인에 이미 제 이름이 떠있는 버그가 있습니다.
![image](https://github.com/user-attachments/assets/bda5b5ad-6dd4-4941-ac98-def749449c41)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh 
- 디자인:

**Comment by Cassiiopeia** [comment]
@thswogh 백 문제면 저 assigned해주세요

**Comment by newjinlee** [comment]
버그 확인이 불가능합니다
더 세세한 설명을 부탁드립니다!

**Comment by jihee127** [comment]
@newjinlee 
![Screenshot_20241208_182325_KakaoTalk.jpg](https://github.com/user-attachments/assets/a0339062-018a-4891-bdfd-b3b9c083ad19)

표시해둔 사진을 올려드립니다 ! 
랜딩페이지를 보면 "윤지희님"이라고 적혀있는데
햄버거버튼으로 연 메뉴를 보면 "로그인 후 이용해주세요"라고 적혀있습니다.

아마 이전에 로그아웃을 안 하고 끄면 생기는 오류 같습니다.
확인 부탁드립니다~

**Comment by Cassiiopeia** [comment]
@jihee127 사진으로 잘 보이는데요

실제 test.sejong-malsami.co.kr

현재 해당버그가 재현이 안됩니다

어떤 상황에서 저렇게 다르게 뜨는지 확인부탁드립니다

**Comment by jihee127** [comment]
@Cassiiopeia 

아예 처음 접속했을 때는 "종이님"으로 뜨고
로그인 이후 **로그아웃 없이 사이트를 나갔다가**
다시 접속하면 로그인은 되어있지 않지만 "윤지희님"으로 이름이 떠있습니다.

**Comment by Cassiiopeia** [comment]
@thswogh  @newjinlee 저도 재현됩니다 수정 부탁드려요

**Comment by newjinlee** [comment]
이슈 중복되어 닫습니다
#315
