### ISSUE TITLE
❗ [버그][질문상세] "채택됨" 태그 버그

### ISSUE THREAD

**Issue by jihee127** [Sejong-Balsamic/Malsami-FE#266]
🗒️ 설명
---
- 질문에서의 "채택됨" 태그와 답변에서의 "채택됨" 태그가 묘하게 다르게 생겼습니다
- 질문: 프리텐다드 볼드, 답변: 프리텐다드 미디움
- 질문: padding 좌우 14px, 답변: padding 좌우 15px
- 질문: Role generic, 답변: Role button

![image](https://github.com/user-attachments/assets/bcc7312b-0d2e-4163-ac04-1b81abc558c3)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee 
- 디자인:

**Comment by Chuseok22** [comment]
@jihee127 확실히 디자이너는 다르다...!!👍

**Comment by newjinlee** [comment]
수정되었습니다 확인해주세요
![image](https://github.com/user-attachments/assets/70e9241d-c5ea-4ec9-9e53-02d8ad45d36f)
![image](https://github.com/user-attachments/assets/a7fa2e0a-121f-4dd1-965b-06f45c6aa240)

**Comment by Cassiiopeia** [comment]
@jihee127  확인해보시고 이슈 닫아주십쇼

**Comment by jihee127** [comment]
확인했습니다~
