### ISSUE TITLE
❗ [버그][질문작성] 작성완료 폰트 다른 버그

### ISSUE THREAD

**Issue by jihee127** [Sejong-Balsamic/Malsami-FE#270]
🗒️ 설명
---
- "작성완료" 버튼 폰트가 다릅니다! 프리텐다드가 아니에요

![image](https://github.com/user-attachments/assets/8d6104b0-fd53-44b4-bd86-8476decbb15b)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh 
- 디자인:

**Comment by thswogh** [comment]
<img width="368" alt="image" src="https://github.com/user-attachments/assets/0d29b9dc-25b7-45c5-9d63-c9be0f20565e">
수정했습니다!

**Comment by jihee127** [comment]
수고하셨습니당~
