### ISSUE TITLE
❗ [버그][답변] 질문 답변시 원문보기 부분 ">" 부재 및 질문글 제목추가

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#274]
🗒️ 설명
---
- 해당부분 원문보기 ">" 이부분 추가하는것으로 알고있는데 맞나요??
- 그리고 원문보기보다는 질문제목도 추가하여야할것같습니다. 
내용만 보여주면 무슨내용인지 잘 이해가안가서요
사진도 추가하여야할것같아요~~

## 정리
- [ ] 원문보기 옆 ">" 추가
- [ ] 답변 -> 원문보기 클릭시 -> 원글 제목, 내용, 사진 3개가 같이 보여야합니다

![image](https://github.com/user-attachments/assets/d5008ffa-ce1e-4780-9a16-a5da694983c9)
![image](https://github.com/user-attachments/assets/4cdfb6c9-c926-4c72-96f9-7288c2ba8845)

![image](https://github.com/user-attachments/assets/c0584443-8d7c-48d7-aa2f-0a2e8d35c3af)
![image](https://github.com/user-attachments/assets/dd7f299a-6dec-47cc-8ef1-56cc70c15c57)

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
@seonglim 질문 등록 페이지 중 원문 보기 부분의 레이아웃을 수정해달라는 것 같습니다 ~
지금: 본문
수정방안: 제목 - 본문 - 첨부파일
부탁드립니다 ~

**Comment by Cassiiopeia** [comment]
> @seonglim 질문 등록 페이지 중 원문 보기 부분의 레이아웃을 수정해달라는 것 같습니다 ~ 지금: 본문 수정방안: 제목 - 본문 - 첨부파일 부탁드립니다 ~

덧붙이자면 첨부파일이라고하면 이미지파일만 의미합니다
질문쪽은 이미지밖에 못올려요~~ 해당사항을 보여주어야합니다
