### ISSUE TITLE
🎨⚙️ [디자인][기능추가] 검색결과페이지 자료게시판 카드 디자인 수정

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-FE#276]
🗒️ 설명
---
### 피그마에 디자인 되어있는 `검색결과페이지->자료게시판`은 게시판등급 필터링이 있습니다
![image](https://github.com/user-attachments/assets/8bc0d341-11c5-4137-b9ad-e2fccc14c399)
<br/>

### 논의 후 필터링 기능을 빼자고 해서, 카드 디자인을 `게시판등급`을 표시할 수 있게 수정해야 할 것 같습니다
디자인 부탁드립니다~
![image](https://github.com/user-attachments/assets/852ed050-217e-4b30-96c7-ba9d0177d971)

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by Vhime** [comment]
에... 태그 검색 뺀다고여?

**Comment by Cassiiopeia** [comment]
> 에... 태그 검색 뺀다고여?

네네 일부러 게시판별 검색기능보다는 키워드로 검색을하고 자료글을 열람시 포인트 부족 알람이 뜨면서 차단하려고합니다

그렇게되면 사용자들도 엽전을 모으려고하겠죠? 애초에 검증되지않은 자료 를 보여주는 필터링이 있어서 좋을게없을것같습니다

**Comment by Vhime** [comment]
<img width="293" alt="스크린샷 2024-12-03 오후 3 41 12" src="https://github.com/user-attachments/assets/3221e9d0-c900-4161-8e19-3e58f591c3dd">
태그 빼고 게시판 넣기

**Comment by Vhime** [comment]
태그 두개가 다 안 들어가
제목 네글자 밖에 못 보여줌
@thswogh
