### ISSUE TITLE
🎨⚙️[디자인][기능추가] 검색결과페이지 검색창 디자인 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-FE#280]
🗒️ 설명
---
기존 검색창은 하나의 검색어만 입력가능합니다
![image](https://github.com/user-attachments/assets/7f302c77-603f-4cc8-a6cf-b7d7f1da75c0)
<br/>
검색창에 교과목명 검색하는 기능이 추가되었습니다
교과목명 검색은 `@`을 이용해서 검색하고 `@`을 입력하면 예상 검색어가 나옵니다.
아래 이미지 참고해서 디자인 해주세요~
![image](https://github.com/user-attachments/assets/1d1db32c-80fc-4984-a5f2-bdc93006598e)
<br/>
![image](https://github.com/user-attachments/assets/f8c02c01-4deb-4066-b645-dd75764109e2)

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by Vhime** [comment]
?

**Comment by Vhime** [comment]
굳이 기호에서 @ 눌러야한다는게 별론데...
과목명 치면 알아서 창에 뜨게는 안 되는지
<img width="380" alt="스크린샷 2024-12-02 오후 11 31 43" src="https://github.com/user-attachments/assets/dcf6a3ef-00de-4752-aa78-871c36499012">

ㅇㄸㅇ @thswogh

**Comment by thswogh** [comment]
근데 과목명이랑 일반검색어랑 분리를 해야하는데 어떻게 디자인하면 좋을지

**Comment by Vhime** [comment]
옆에 과목명이라 해주...느..ㄴ...ㅋㅋㅋ....
아님 그 대양휴머니티칼리지 이런거.. 달아주기...
아님 과목명 / 추천검색어 창 나누기

**Comment by thswogh** [comment]
새찬님께서 검색 두번하는게 귀찮다고 하셔가지고 이렇게 된거긴 합니다만ㅋㅋㅋ

**Comment by Vhime** [comment]
한번에 떠야...
여러개 작업 해볼게

**Comment by Vhime** [comment]
<img width="894" alt="스크린샷 2024-12-03 오전 12 02 39" src="https://github.com/user-attachments/assets/22693a1f-aac9-4f77-b217-9717c2573a57">

@thswogh

**Comment by Vhime** [comment]
@ 치기 싫단말야 ~~~~~ 과목명 바로 뜨면 좋겟단말야 ~~~

**Comment by Cassiiopeia** [comment]
@Vhime 아니~

과목명을 검색하는게 아니라

어떤 과목명에 내용도 입력할수있잖아

**Comment by Vhime** [comment]
그게 필터링이랑 뭐가 다른데...

**Comment by Cassiiopeia** [comment]
@Vhime @thswogh 
https://youtu.be/nJPsvCHM0dQ?t=251

해당 영상 참고부탁드립니다

![image](https://github.com/user-attachments/assets/1bea2ed6-255d-440a-a650-621d34b009f0)

**Comment by Vhime** [comment]
<img width="375" alt="스크린샷 2024-12-03 오후 3 36 54" src="https://github.com/user-attachments/assets/f78e896e-ecbf-4317-8cfa-566aa1fc20f2">
ㅇㄸㅇ
@thswogh

**Comment by thswogh** [comment]
돌아가게 하나요? 아니면 `@공간과인간 기말과제` 하나만 띄어놓을까요? @Vhime

**Comment by Vhime** [comment]
돌아가 ~~~

**Comment by thswogh** [comment]
검색 시, `교과목명`과 `일반검색어` 나누어 검색 가능하게 구현했습니다.
css보다는 기능위주로 보고 피드백 부탁드립니다

https://github.com/user-attachments/assets/cbc3c2c6-0655-40f5-b1a6-e6216bef1b85

**Comment by Cassiiopeia** [comment]
#307  해당이슈와 동일하여 이슈 닫습니다
