### ISSUE TITLE
⌛🎨🔧[~12/10][디자인][기능요청]추가 일러 요청 - 404 페이지 / 첫 로그인 모달 

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-FE#284]
🗒️ 설명
---
- 추가 일러 요청합니다 ~

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee 
- 디자인: @seonglim

**Comment by Cassiiopeia** [comment]
@newjinlee 해당부분 작업되었나요?
