### ISSUE TITLE
❗ [버그][랜딩페이지] 랜딩페이지 이스터에그 버그

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#292]
🗒️ 설명
---
- 로그인 하지않은 상태로 이스터에그 클릭 시 작동하는 버그가 존재합니다.
- 이스터에그를 발견하면 엽전을 획득하기 때문에 로그인 하지 않은 경우 이스터에그가 작동하면 안될 것 같습니다.
![스크린샷 2024-12-06 오후 1 38 24](https://github.com/user-attachments/assets/a4e6d7e0-d84b-4713-acdd-3b18082febac)
![스크린샷 2024-12-06 오후 1 38 40](https://github.com/user-attachments/assets/f16a0b3c-fa3d-4bec-b05f-b3cee051db5c)

- 바퀴벌레 발견~~

https://github.com/user-attachments/assets/1d38ecfc-06d1-41e3-93bf-676cb247496a

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh 
- 디자인:

**Comment by newjinlee** [comment]
이스터에그에 버그라니요 ㄹㅇ 너무들 하시네

**Comment by thswogh** [comment]
랜딩페이지는 로그인 유무를 확인할 수가 없어서 로그인 되어 있는지, accessToken이 유효한지 확인하는 api가 필요할 것 같습니다.
더 좋은 방법 있으면 코멘트 남겨주세요~

**Comment by thswogh** [comment]
@Chuseok22 
로그아웃 상태에서 이스터에그로 엽전 획득 불가하게 수정했습니다
확인부탁드립니다~

**Comment by Chuseok22** [comment]
확인했습니다~ 이슈 닫을게요
