### ISSUE TITLE
❗ [버그][랜딩페이지] 랜딩페이지에서 더보기 클릭 시 무한로딩

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#294]
🗒️ 설명
---
- 로그인하지않은 상태로 랜딩페이지에서 전체 자료게시판 및 질문게시판 더보기 버튼 클릭 시 해당 게시판으로 이동합니다.
- 토큰이 없는 경우 랜딩페이지에서 액션이 들어오면 "로그인 후 이용 가능합니다." alert창과 함께 로그인 페이지로 이동해야할 것 같습니다.
- 전체 질문게시판 더보기 접근 시 로딩 화면이 계속 출력됩니다.
- 또한 로그인하지 않은 상태로 검색 창에서 검색 시에도 같은 문제가 발생합니다.

https://github.com/user-attachments/assets/8c641fed-1712-4ac0-970d-01e7d3ffd56b

🙋‍♂️ 담당자
---
- 백엔드:
- 프론트엔드: @newjinlee @thswogh 
- 디자인:

**Comment by newjinlee** [comment]
로그인 상태에 따라 연결되는 페이지가 다르게 수정했습니다!
확인해주세요

**Comment by Cassiiopeia** [comment]
#293  무한로딩은 고쳐졌지만 토큰없을때 로직이 문제가있는것같아서 

해당 일감에서 해결하는걸로 했습니다. 이슈 내립니다
