### ISSUE TITLE
❗ [버그][질문상세] '채택됨' 태그 클릭 시 색상 사라짐

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#295]
🗒️ 설명
---
영상으로 보면 바로 이해될 거에요 ㅎㅎ

https://github.com/user-attachments/assets/bf6a8321-4a9a-4072-8731-82d02e45016c

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee 
- 디자인:

**Comment by newjinlee** [comment]
#266 에서 해결한 이슈라 닫겠습니다
