### ISSUE TITLE
❗ [버그][질문게시판] 아직 답변하지 않았어요! 카드 정적태그 길이 문제

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#297]
🗒️ 설명
---
- 정적태그 길이가 긴 태그를 2개 적용하게되면 해당 태그가 두줄로 출력되는 문제가 발생합니다.
- 또한 출력해야 할 카드의 개수가 1개일경우 왼쪽에 정렬되는 것이 맞는지 확인 부탁드립니다. (이부분은 디자이너 예진님이랑 상의 후 결정하면 될 것 같습니다)
![스크린샷 2024-12-06 오후 2 50 56](https://github.com/user-attachments/assets/09c007ab-0b8f-4941-8869-72e457f659f0)
![스크린샷 2024-12-06 오후 2 51 01](https://github.com/user-attachments/assets/458ae4e5-7263-484b-9697-64e26287a442)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by Vhime** [comment]
그래서 태그 하나로 하자고

**Comment by Cassiiopeia** [comment]
> 그래서 태그 하나로 하자고

@Vhime 그래서 걸론이 어케남?

**Comment by newjinlee** [comment]
assignee에서 저는 빠질게요 ~

**Comment by thswogh** [comment]
- 1개일 때 왼쪽정렬이 맞는 것 같습니다!
- 특정 태그가 2개가 되면 (더나은풀이, 수업외내용) 태그가 2줄로 표시되는 문제가 있습니다. 
태그를 1개만 보여주는 것도 방법일 수 있겠지만, 유저가 글을 올릴 때 애초에 태그를 최대2개 선택 가능하니 2개를 다 보여주는 것이 좋다고 생각합니다.
카드의 width를 고정하고 화면이 커지면 보여지는 카드 개수를 늘리는 방식으로 구현했습니다. 태그의 길이를 줄이기 위해 태그의 띄어쓰기를 없앴습니다.
<img width="664" alt="image" src="https://github.com/user-attachments/assets/f0cdd024-2e28-4f2c-8925-fd3fbfd1aa5a" />

**Comment by Cassiiopeia** [comment]
![image](https://github.com/user-attachments/assets/199a77b6-48ed-4c89-b0e6-a0b6a8df7dae)

해당부부분 수정 부탁드립니다

태그없으면 저부분이 떠서 보이는게 맞나요??

@Vhime

**Comment by thswogh** [comment]
수정했습니다
#358 

<img width="377" alt="image" src="https://github.com/user-attachments/assets/dba031cc-e5df-407d-8f6f-2b73cd1805cd" />

**Comment by Cassiiopeia** [comment]
@thswogh 확인했습니다 고생하셨습니다 이슈닫습니다
