### ISSUE TITLE
❗ [버그][질문게시판] 답변 작성 후 뒤로가기 버튼 클릭 시 답변 작성 페이지로 돌아가는 버그

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#298]
🗒️ 설명
---
- 질문게시판 답변 등록 후 뒤로가기 버튼 클릭 시 답변 작성 페이지로 돌아가는 버그가 있습니다

https://github.com/user-attachments/assets/4969b0bd-a333-49fc-a716-2a4be148426e

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee 
- 디자인:

**Comment by Cassiiopeia** [comment]
저 상세페이지에서 뒤를 누르면 무조건 목록으로 가게해야죠

**Comment by newjinlee** [comment]
모바일로 접속할 경우 아래에 브라우저에서 제공하는 뒤로가기 버튼이 따로 있어 목록으로 연결하는 것도 나쁘지 않을 것 같네요? 갤럭시도 브라우저에서 뒤로가기 버튼을 제공하나요?
![image](https://github.com/user-attachments/assets/50d1bd49-1e96-44c1-b458-205fcc38cf54)

**Comment by newjinlee** [comment]
자료 상세와 질문 상세 모두 Nav의 < 버튼을 누르면 각각 메인페이지로 연결되게 수정했습니다.
확인해주세요

**Comment by newjinlee** [comment]
좋은 시도였다
