### ISSUE TITLE
❗ [버그][질문게시판] 하단 페이지네이션 통일성

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#299]
🗒️ 설명
---
- 질문게시판 목록에서 하단 페이지네이션은 단일 페이지, 다중 페이지 모두 존재하는 것 같습니다.
- 단과대 "예체능대학"필터링 시 하단 페이지네이션이 사라지는 버그가 존재합니다.
- 예상하자면 1페이지 최대 개수를 채우지 못하면 페이지 번호 자체가 사라지는 것 같습니다
- 단과대 "대양휴머니티칼리지"선택시 정확히 글 개수가 16개가 됩니다. 이 경우에는 1페이지 최대개수를 만족하여 하단 페이지번호가 나타나는 것 같습니다
- 통일성있게 수정해주시면 감사하겠습니다~
![스크린샷 2024-12-06 오후 3 06 25](https://github.com/user-attachments/assets/f0b2acfd-9f32-4022-a84a-d7131eba2437)
-> 다중 페이지
![스크린샷 2024-12-06 오후 3 06 37](https://github.com/user-attachments/assets/413da5d8-4b69-4c28-a002-5b11dc9c9711)
-> 단일 페이지
![스크린샷 2024-12-06 오후 3 07 34](https://github.com/user-attachments/assets/dd8eab4b-3ba1-46db-8e67-eef6160f96e1)
-> 단과대 "예체능대학" 필터링 시
![스크린샷 2024-12-06 오후 3 08 41](https://github.com/user-attachments/assets/a024c84f-a502-42c5-9be7-325d3ded7c6d)
-> 단과대 "사회과학대학"필터링 시

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh 
- 디자인:

**Comment by thswogh** [comment]
하단 페이지네이션 수정하였습니다!
![image](https://github.com/user-attachments/assets/cbe81d4d-ef49-47e1-a8da-b3f97b688b73)

**Comment by Cassiiopeia** [comment]
1페이지에서 오류가 발생하는데요

엑박오류 해결 부탁드립니다

그리고 최하단에 내려갔을때

플로팅버튼과 페이지네이션 버튼과 겹침이 발생하는데요
해당부분 플로팅버튼이 표시되지않게 변경 부탁드립니다

<img width="391" alt="image" src="https://github.com/user-attachments/assets/e81f5675-06f9-434d-93df-bf0bc7a3c777" />

**Comment by Cassiiopeia** [comment]
#327  해당부분으로 이전하여 작업 부탁드립니다
