### ISSUE TITLE
❗ [버그][질문게시판] 페이지 버그

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#300]
🗒️ 설명
---
- 현재 페이지는 1~5페이지까지만 이동가능한 버그가 있습니다
- 한 페이지게 16개의 글을 보여주며 총 80개의 글만 열람할 수 있습니다.
- 더 많은 페이지를 이동할 수 있게 변경해야할 것 같습니다
- 현재 질문글 데이터는 충분히 DB에 넣었습니다
![스크린샷 2024-12-06 오후 3 16 24](https://github.com/user-attachments/assets/e42969a6-b316-49da-b360-a654c67d9299)
---------------------------------------------------------------------
`긴급`
@Vhime 
@thswogh 
@newjinlee 
- 현재 5페이지에서 6페이지로 넘어갈 수 있는 방법이 '다음'버튼을 눌러야합니다
- '다음'버튼이 글쓰기 버튼하고 겹치는 문제가 있어 불편함이있습니다
![스크린샷 2024-12-06 오후 3 22 22](https://github.com/user-attachments/assets/8b3822b0-716b-427a-9116-df3aa91cf39a)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @thswogh @newjinlee 
- 디자인: @Vhime @jihee127

**Comment by thswogh** [comment]
아직 페이지네이션을 구현하지 않아서 그렇습니다..

**Comment by Vhime** [comment]
아하

**Comment by Vhime** [comment]
것보다 페이지네이션 바꿔주세요..

**Comment by Chuseok22** [comment]
저거 플로팅버튼이랑 다음버튼 겹치는거 해결가능해여??

**Comment by Cassiiopeia** [comment]
> 저거 플로팅버튼이랑 다음버튼 겹치는거 해결가능해여??

@Chuseok22 이거 따로 이슈 올려야할것같아요

placeholder 구현이 필요해보이는것으로 이슈올리면될것같습니다

**Comment by Cassiiopeia** [comment]
해당 이슈는 페이지네이션을 구현하는 기능이 없는것 이므로 새로운 기능요청 이슈를 올리겠습니다
