### ISSUE TITLE
❗ [버그][랜딩페이지] 랜딩페이지 특정 글 클릭시 해당 글로 이동 안되는 버그

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#301]
🗒️ 설명
---
- 인기글의 경우 카드를 클릭하면 해당 글로 이동합니다
- 전체 게시판에 썸네일로 보여주는 5개의 글의 경우 제목 및 본문을 클릭해도 해당 글로 이동하지 않습니다
- 의도된 기능이면 이슈 닫아주시면 감사하겠습니다~
- (추가) 자료게시판 랜딩페이지에서 보여주는 1위~5위 글은 클릭 시 해당 글로 이동합니다 -> 메인랜딩과 자료랜딩 부분 통일하면 좋을 것 같아요 ㅎㅎ
![스크린샷 2024-12-06 오후 3 26 08](https://github.com/user-attachments/assets/5516e47b-aa9e-42e8-bb14-06d9118b5a9e)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee 
- 디자인:

**Comment by newjinlee** [comment]
전체 게시판 카드에서 각각 상세페이지로 연결했습니다!
확인해주세요

**Comment by Cassiiopeia** [comment]
확인했습니다~ 이슈 닫습니다
