### ISSUE TITLE
❗ [버그][자료게시판] 자료게시판 랜딩페이지 카드 클릭 시 입장제한 후 페이지 이동

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#302]
🗒️ 설명
---
- 자료게시판 랜딩페이지에 올라와있는 HOT다운로드, 내 전공 관련 자료, 주간 인기 자료글에 있는 글 클릭 시 엽전이 부족하여 해당 글을 열람할 수 없을 때 "사용자의 엽전이 부족합니다." 라는 alert 창이 뜬 뒤, 하얀색 화면이 계속 출력됩니다 ㅠㅠㅠ

https://github.com/user-attachments/assets/31d87568-14ac-421f-a982-2f63d416245c

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee 
- 디자인:

**Comment by newjinlee** [comment]
not me ~

**Comment by thswogh** [comment]
수정했습니다~

**Comment by Cassiiopeia** [comment]
> 수정했습니다~

어떤식으로 수정했는지 상세 설명 부탁드립니다

**Comment by thswogh** [comment]
api 호출하는 코드에 isMounted 변수를 설정해, 불러오고자 하는 컴포넌트가 렌더 트리에 존재할 때만 에러를 캐치해 뒤로가기 할 수 있게 구현하였습니다.

**Comment by Chuseok22** [comment]
어후 다음 이슈부터는 화질 좀 개선해서 올릴게요...ㅎㅎ 480p는 좀 너무했네 ㅋㅋㅋㅋ
@thswogh 테스트 해보셨나여...?

**Comment by Chuseok22** [comment]
> 어후 다음 이슈부터는 화질 좀 개선해서 올릴게요...ㅎㅎ 480p는 좀 너무했네 ㅋㅋㅋㅋ @thswogh 테스트 해보셨나여...?


https://github.com/user-attachments/assets/f7a74a51-fb70-4fdc-867f-effa7a0b8ebc

**Comment by thswogh** [comment]
@Chuseok22 이렇게 바꾸는거 괜찮을까요? 더 좋은 인터페이스 있을까요?
https://github.com/user-attachments/assets/1a0f48c2-3f30-4195-90b4-77ea6f6d07fe

**Comment by thswogh** [comment]
토스트 말고 모달창으로 바꾸기로
