### ISSUE TITLE
❗ [버그][카테고리] 자료게시판 랜딩페이지 카드 사이즈

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-FE#303]
🗒️ 설명
---
- 자료게시판 랜딩페이지에 작성 된 카드 중 사이즈가 다른 카드가 있습니다
![스크린샷 2024-12-06 오후 3 39 10](https://github.com/user-attachments/assets/b832b233-4a88-4e36-b9b4-fd81d392adc0)
![스크린샷 2024-12-06 오후 3 38 54](https://github.com/user-attachments/assets/fc09a1ab-0aaa-408b-b4bb-03abdb4722e8)
![스크린샷 2024-12-06 오후 3 41 28](https://github.com/user-attachments/assets/c8984151-c856-41bd-9a63-883f079c57ef)

🙋‍♂️ 담당자
---
- 백엔드: 
- 프론트엔드: @newjinlee @thswogh 
- 디자인:

**Comment by newjinlee** [comment]
not me ~

**Comment by thswogh** [comment]
수정했습니다
<img width="609" alt="image" src="https://github.com/user-attachments/assets/f7209b57-eb6b-42c5-b256-2f86dda7a787" />

**Comment by Cassiiopeia** [comment]
@thswogh  확인했습니다

@newjinlee 랜딩페이지도 동일 증상 있습니다

확인부탁드립니다

<img width="383" alt="image" src="https://github.com/user-attachments/assets/31595010-3973-40a0-b255-ffc13034c886" />

**Comment by newjinlee** [comment]
@Cassiiopeia 랜딩에서 해당 증상 찾아볼 수 없습니다. 질문 메인의 카드와 랜딩의 카드가 같은 컴포넌트를 사용하고 있어 저절로 해결된 것 같습니다~ 확인부탁드립니다

**Comment by Cassiiopeia** [comment]
네네 확인되었습니다 이슈닫습니다
