### ISSUE TITLE
⌛🎨🔥 [~12/17][디자인][자료상세] 자료 다운로드 버튼 개선 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#306]
🗒️ 설명
---
- 자료 다운로드 버튼의 개선이 필요해보입니다
- 저희 주 목적이 이런 자료를 올리는거였는데요. 너무 디자인이 좀... 그래요

세종말싸미에 맞는 디자인으로 한번 부탁드립니다

그리고 한가지 더 첨가해야할것은 

내가 이 자료를 구매했는지 여부를 이 글에 들어갔을때 알수있어야합니다

내가 질문게시판에 들어갔을때 좋아요를 눌렀었는지를 확인하는것처럼요

그리고 자료구매내역이랑 지금 자료게시판 상세랑 다 다르네요....

# 왓?

<img width="463" alt="image" src="https://github.com/user-attachments/assets/18746acb-d09e-4511-a126-23b6621c2cff">

![image](https://github.com/user-attachments/assets/a2861071-9b37-43b1-bc33-8d4ed2eecabb)

-------

<img width="386" alt="image" src="https://github.com/user-attachments/assets/d86c2ec8-dac8-4475-92d2-f98e719a7443">

<img width="384" alt="image" src="https://github.com/user-attachments/assets/38584c9c-e2c0-44c1-90b1-0f058220ffdf">

🙋‍♂️ 담당자
---
- 디자인: @jihee127 @Vhime

**Comment by newjinlee** [comment]
추가로 
만약 첨부파일의 이름이 길 경우 어디서 잘라야 하는지, 어떻게 잘라야 하는지도 추가 디자인해주시면 좋겠습니다 ~
![image](https://github.com/user-attachments/assets/ebe1d713-f06d-4f72-913a-1d51fadcc1cc)

**Comment by newjinlee** [comment]
버튼에 추가로 썸네일도 넣어주시면 감사합니다 ~

**Comment by newjinlee** [comment]
모달도 같이 해주시면 땡베감입니다 ~
