### ISSUE TITLE
⌛🎨 [~12/17][디자인][검색] 검색시 @버튼을 눌렀을경우 어떤식으로 떠야하는지 디자인 요청

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#307]
🗒️ 설명
---
- 요청하는 기능에 대한 간단한 설명을 작성합니다.

현재 @을 눌렀을때 교과목명을 검색해야하는데 
이부분에서 눌렀을때 어떤 UI로 표시할지 디자인 부탁드립니다

카톡화면 예시로 보여드립니다

<img width="438" alt="image" src="https://github.com/user-attachments/assets/d1337845-9e81-4967-b3af-bd7aaf756a97">

![image](https://github.com/user-attachments/assets/fb12ed5b-1880-4cfe-bc5e-a64337777c60)

🙋‍♂️ 담당자
---
- 디자인: @Vhime

**Comment by Cassiiopeia** [comment]
@Vhime 만약 골뱅이로 검색을 하면

<img width="372" alt="image" src="https://github.com/user-attachments/assets/d378aacc-8699-4fef-baaa-4dbfd7661585">


이런식으로 표시되는게 아니라 @가 포함됨 검색어로 표시되어야될것같은데요

고민한번 해보시고 디자인 부탁드립니다.


그리고 X가 너무커요! 원래 다른곳도 이렇게 크게 표시하나요? ㅎㅎ

**Comment by Vhime** [comment]
작으면 안 보이자나용...

**Comment by Cassiiopeia** [comment]
<img width="392" alt="image" src="https://github.com/user-attachments/assets/d4fa252b-99b2-4d55-a262-105e580f20cf">

**Comment by Cassiiopeia** [comment]
@Vhime 디자인 피드백 부탁드립니다

@thswogh  로직적인 피드백을 말해보자면....
@유 를 검색했을때 현재 %유% 이런식으로 앞뒤 사이에 유가 있는 경우를 검색하는것같은데
보통 교과목 검색할떄 유라는 글자가 들어가있는지를 검색하지않지않나요
저는 보통 유로 시작하는 교과목을 검색할것같은데

아니면 성능개선을 위해서라면 고려해볼꼐

이게 한글자이면

유%

뒤만 검색하고

검색어가없으면 표시하지말고


%유기%

이렇게 두글자이면
앞뒤를 포함한 단어를 검색하고 그런식으로 하는게 좋지않나요

한글 자음모음 한글자한글자 칠떄마다 검색을해서 살짝 버벅거리는것같은데
입력이 시작된 후로 0.7초정도 입력이없을떄 검색하던지 그런식으로 해결할수도있을것같고요

생각하니 나름이긴한데 검색속도는 둘쨰치고 한모음 자음 칠떄 버벅거리는건 아쉽네요

![image](https://github.com/user-attachments/assets/310b8c2f-04b6-4309-bc3c-93b7820b751b)
