### ISSUE TITLE
🔥 ❗[긴급][버그][질문메인] 보안중대위험 memberId 정보와 회원명이 session에 저장되는 문제 

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#315]
🗒️ 설명
---
- memberId 와 회원명이 현재 브라우저 session정보에 저장되어있습니다
- 현재 이런정보들이 밖으로 노출되어서는 안됩니다. 보안사항이므로 긴급으로 처리합니다

회원정보를 가져오는 방법은 api도 있으며  프론트상에서도 내부적으로 안전곳에 저장하는 방법으로 처리해주세요

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/4de0727e-d6ae-4916-9e58-bda6648b5199">

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee

**Comment by newjinlee** [comment]
accessToken만 저장되게 수정했습니다! 로그인 안해도 랜딩에 이름 뜨는 버그도 같이 수정됩니다.
확인해주세요
![image](https://github.com/user-attachments/assets/d41cd802-1367-4525-80ee-cbd236fe06b2)

**Comment by Cassiiopeia** [comment]
확인되었습니다 고생하셨습니다
