### ISSUE TITLE
🔥❗[긴급][버그][질문메인] 교과목명이 첫번재로 오도록 태그 중요도 수정 및 태그 통일성 수정 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#316]
🗒️ 설명
---
- 현재 질문메인에서 리스트에 보이는 태그가 순서가 : 엽전현상금 - 교과목명입니다
- 질문상세에서 보이는 태그의 순서가 : 교과목명 - 엽전현상금입니다

## 모든 구간에서 교과목명이 먼저 나오게해주세요

<img width="391" alt="image" src="https://github.com/user-attachments/assets/593f87e9-c4d3-400f-94dc-dd3b206df397">

옳은 예시

<img width="388" alt="image" src="https://github.com/user-attachments/assets/ac1b7697-ebca-4e41-8089-40ae6c87bd4a">

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee

**Comment by thswogh** [comment]
교과목명이 먼저 나오게 카드 UI 수정했습니다
<img width="628" alt="image" src="https://github.com/user-attachments/assets/58c6a2a9-0949-4300-a221-b738f3ad82c7">

**Comment by Cassiiopeia** [comment]
확인했습니다 이슈닫습니다
