### ISSUE TITLE
🔧 [기능요청][API] 회원 엽전 및 자료게시판접근가능정보 반환 API 엔드포인트 주소 수정

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#318]
🗒️ 설명
---
- 현재 다음 주소로
- 회원의 엽전정보 , 자료게시판 접근여부 값들에 대해서 받을수있습니다
<img width="611" alt="image" src="https://github.com/user-attachments/assets/eb7bd02b-ce5a-437b-883e-fc66a2304828">

해당부분의 URL주소가 올바르지않다고 생각하여
다음과 같이 수정하였습니다
<img width="542" alt="image" src="https://github.com/user-attachments/assets/d181521b-e267-4d3c-8906-d4eab21b444b">

/api/member/document/access-info -> /api/member/yeopjeon-info

수정 부탁드립니다

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee

**Comment by thswogh** [comment]
엔드포인트 변경했습니다
