### ISSUE TITLE
⚙️❗ [버그][기능추가][폰트] 폰트 적용

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-FE#320]
🗒️ 설명
---
저희 프로젝트에서는 Pretendard 폰트를 적용하고 있었는데, 모든 컴퓨터 시스템에 일반적으로 깔려있지 않습니다
기존 사파리에서만 폰트적용이 안되는 줄 알고 있었는데, 사실 모든 곳에서 폰트 적용이 안되고 있었습니다..

폰트를 적용하는 방법은 크게 2가지 방법이 있습니다.
1.  CDN 방식 (Content Delivery Network)
2. Assets에 저장 (로컬 파일로 저장)

> 저희는 CDN방식으로 외부폰트를 적용하고자 하였습니다

CDN 방식은 서버에 폰트를 저장하지 않고, URL을 통해 폰트 파일을 로드하고 보여주는 방식입니다.
따라서 브라우저가 로드될 때, 비동기적으로 다운로드받을 수 있는 URL을 추가해주어야 합니다.

#### 문제발견
문제 디버깅을 위해 tailwind.config.ts파일과 global.css파일을 모두 확인해봤지만 서로 필요한 변수를 잘 사용하고 있었습니다. 
마지막으로 의심했던 부분이 바로 CDN방식에서 사용하는 URL주소였습니다.
개발자도구에서 폰트를 정상적으로 다운로드하는지 확인할 수 있는데 확인방법은 다음과 같습니다.
`크롬웹브라우저 > 개발자도구 > Network > Font`
확인해보니 다음 사진과 같이, 다운로드하는 폰트가 없었습니다.
<img width="759" alt="image" src="https://github.com/user-attachments/assets/78073a8a-c119-4fe4-b03f-f9eb97308e7a">

#### 문제해결
pretendard폰트를 불러오는 잘못된 url을 수정해주니, 오류를 해결할 수 있었습니다. 
하지만 pretendard를 지원하는 [Github주소](https://github.com/orioncactus/pretendard)에 있는 url을 사용해도 정상적으로 다운로드 되지 않는데 이 부분은 추후에 이유를 찾아보고 우선은 폰트깨지는 이슈 해결..!

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee @thswogh

**Comment by thswogh** [comment]
@Cassiiopeia 혹시 궁금해하실까봐 적어봤는데.. 보고 이슈 닫아주세요

**Comment by Cassiiopeia** [comment]
@thswogh 

현재 프리텐다드 폰트을 가지고있는 사람들한테서는 프리텐다드로 보이는것까진 해결 

이전에는 이것도 안되어서 프리텐다드 폰트가 있어도 적용도 안되고있었음 

이거인가요??

현재 프리텐다드가 없는 사람른 프리텐다드 폰트가 적용될수없다 인가요??
다운로드가 안되니까??

그럼 새로운 이슈작성을 해야하나요??

**Comment by newjinlee** [comment]
프리텐다드가 없는 사람은 프리텐다드 폰트가 적용될 수 없었는데, CDN 방식으로 웹폰트를 불러와 글씨체를 적용했습니다. 문제 없이 폰트 적용 잘 되고 있습니다!

**Comment by newjinlee** [comment]
#319 
해당 이슈 링크합니다
