### ISSUE TITLE
🔧 [기능요청][페이지로딩] 페이지 로딩할시 기본적인 스켈레톤(placeholder)를 구현 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#325]
🗒️ 설명
---
- 현재 몇몇개의 주소에 로딩하는 시간이 오래걸려서 사용자가 핸드폰이 문제인건지 브라우저가 문제인건지 알수없는 상황이 발생하는것같습니다
- 그런 페이지들에 대해 스피너 ui를 도입한것으로 알고있는데 이런부분에 대해서 스피너보다는 데이터를 가져오는 동안 콘텐츠를 표시하는 컴포넌트가 필요할것같습니다. 페이지를 로딩하는데 지연시간이 걸리는것이니까요

해당부분에 대해서 잘 설명해주는 블로그 주소입니다. 이와 비슷하게 한번 해주세요

https://velog.io/@baby_dev/React%EB%A1%9C-Skeleton-Component-%EB%A7%8C%EB%93%A4%EA%B8%B0

https://semantic-ui.com/elements/placeholder.html

## 공통 기능이니 담당자 두명으로 언급했습니다. 서로 의견 조율해서 구현해주시길바라겠습니다

![image](https://github.com/user-attachments/assets/58d64c05-8c42-433e-af32-324fe1979b0e)

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh @newjinlee

**Comment by Cassiiopeia** [comment]
@thswogh @newjinlee 

## 서로 만든 스켈레톤 ui 가 다르면 이슈가 올라갈수있습니다 잘 조율 부탁드립니다

( 안좋은 사례:  "< 질문게시판" 쪽 nav바 )

**Comment by thswogh** [comment]
확인했습니다
