### ISSUE TITLE
❗ [버그][질문상세] 엽전현상금이 0 일시 태그가 표시되는 문제

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#326]
🗒️ 설명
---
- 질문상세에서 엽전현상금이 없는데 불구하고 엽전현상금 0이 표시됩니다
- 질문리스트에서는 표시되지않는데요 이부분 엽전현상금이 0이면 표시하지않게 수정 부탁드립니다

![image](https://github.com/user-attachments/assets/8d496296-8d21-4647-b35e-693003adc799)
![image](https://github.com/user-attachments/assets/337d0fd6-ba92-406a-aa03-79b83626a37e)

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
수정했습니다. 확인해주세요
![image](https://github.com/user-attachments/assets/a11c647a-1368-4d91-b67e-d021f8cbbe59)
