### ISSUE TITLE
🎨 🔧 [디자인][기능요청][페이지네이션] 페이지네이션이 UI 개선 및 구현 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#327]
🗒️ 설명
---
- 저희의 앱 성격상 무한스크롤보다는
- 페이지네이션을 사용하는것이 옳다고 생각하였습니다
- 현재 페이지네이션 디자인이 나왔는데요

해당부분입니다 
여기에 문제점이 있어보이는데요

이렇게 구현을하면 페이지를 3개씩밖에 넘길수 없다는건가요??

디자인 수정후 -> 손재호님 담당자 지정 부탁드립니다

- 10개? 미만일때 디자인
- 10페이지 이상일떄 디자인 등 베리에이션 디자인이 필요할것같습니다

### 지식인의 페이지네이션 방식입니다
https://kin.naver.com/
![image](https://github.com/user-attachments/assets/49260fab-7d07-4156-b0b2-d6a8e7a9a94c)

### 현재 깃헙의 페이지네이션 방식입니다
https://github.com/Semantic-Org/Semantic-UI/issues
![image](https://github.com/user-attachments/assets/ca83ad7f-b71c-437c-8baf-843cea7bd885)

### 디시인사이드
https://gall.dcinside.com/board/view/?id=dcbest&no=287847
![image](https://github.com/user-attachments/assets/4c117f2c-b12f-42ed-9b33-cda3d437628d)

![image](https://github.com/user-attachments/assets/743bb830-65d4-4887-ab30-8e9953106b12)

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh 
- 디자인: @Vhime

**Comment by thswogh** [comment]
제가 임의로 해보았는데요.. 보고 피드백 부탁드립니다 그냥 accept도 환영합니다
<img width="360" alt="image" src="https://github.com/user-attachments/assets/18ec8a84-3849-44ad-a0d6-235ebe693140" />
<br/>
<img width="360" alt="image" src="https://github.com/user-attachments/assets/d8ac289b-392e-44a1-b534-d3a0cd216a97" />
<br/>
<img width="360" alt="image" src="https://github.com/user-attachments/assets/6aa88e6c-93ac-4b0a-8c1d-fe84a1a4eabe" />

**Comment by Cassiiopeia** [comment]
> pc랑 모바일이랑 비교하는 건 에바지

@Vhime ㅎㅎㅎ죄송죄송

**Comment by Cassiiopeia** [comment]
@Vhime 알아서 close해줘~~ 마지막 디자인 올려주세요

**Comment by Vhime** [comment]
<img width="303" alt="스크린샷 2024-12-13 오후 7 42 48" src="https://github.com/user-attachments/assets/f852b7ba-6519-40ad-973b-0304c9ca6b60" />
@thswogh 

<img width="843" alt="스크린샷 2024-12-13 오후 7 44 01" src="https://github.com/user-attachments/assets/58bbc81e-9f68-417a-86ff-d22b1065ad35" />
pagination width 18px로 고정 후에 중앙 정렬 해주세요
100 이후부터는 알빠노긴 함 일단 급한 불 끄기 ^.^

**Comment by Cassiiopeia** [comment]
@thswogh  추가로 1페이지에서 오류가 발생하는데요

엑박오류 해결 부탁드립니다

그리고 최하단에 내려갔을때

플로팅버튼과 페이지네이션 버튼과 겹침이 발생하는데요
해당부분 플로팅버튼이 표시되지않게 변경 부탁드립니다

<img width="391" alt="image" src="https://github.com/user-attachments/assets/e81f5675-06f9-434d-93df-bf0bc7a3c777" />

**Comment by thswogh** [comment]
@Cassiiopeia  @Vhime 

페이지네이션 디자인 수정했습니다. 
`<<` , `>>`는 어차피 항상 첫번째페이지와 마지막페이지가 사용자한테 보여지기에 뺐습니다.
공간도 부족한거 같아서..
그래도 혹시 넣고 싶다면 코멘트 달아주십셔

<img width="373" alt="image" src="https://github.com/user-attachments/assets/aa110c07-f18f-41f6-9a08-f8f8345a43c7" />
<img width="373" alt="image" src="https://github.com/user-attachments/assets/3cc97136-5247-4d89-8c17-abc58215e592" />

**Comment by Cassiiopeia** [comment]
@thswogh ㅎㅎㅎ 난 이게더깔끔하니 좋구만 ㅎㅎㅎㅎ
@Vhime

**Comment by Cassiiopeia** [comment]
@thswogh @Vhime 

저근데 궁금한게 오른쪽 ">" 버튼을 누르면 다음 페이지 묶음의 첫번쨰인 6으로 넘어가야하는게 맞지않나요?

현재 페이지가 1이고 ">"를 누르면 2를 가는건 의미가있나요? 클릭하면되는것아닌가요?

![image](https://github.com/user-attachments/assets/783d7ac9-15d7-42fe-bcf6-384a73183740)

**Comment by Vhime** [comment]
둘다 되게.. ㅎ?
