### ISSUE TITLE
❗ [버그][질문상세] 본인글에 답변작성 버튼 표시되는문제 및 채택하기 버튼 미표시

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#362]
🗒️ 설명
---
- 의도한건지 모르겠지만 본인이 올린 질문글에 대해서
"답변하기" 버튼은 안보여야 정상인 로직 맞나요?? 보이지않게 수정해야할것같습니다

그리고 저한테 채택하기 버튼이 안보입니다. 채택하기 버튼 있어야하지않나요?

<img width="372" alt="image" src="https://github.com/user-attachments/assets/48a61283-55ab-43ea-8853-5950df4f439e" />

🙋‍♂️ 담당자
---
- 프론트엔드: @newjinlee

**Comment by newjinlee** [comment]
확인했습니다
