### ISSUE TITLE
❗ [버그][답변작성] 본인글 답변작성 등록시 오류 메시지 다중표시

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-FE#363]
🗒️ 설명
---
- 기본적인 상황에서는 본인 게시글에 답변작성으로 오지않을것이지만

답변작성페이지에서 본인 답변등록일떄 일단 오류가 한가지만 표시되어야할것같습니다

## **재호님이 다루는 페이지는 거의 토스트, 모달창 대신 alert창이 표시되던데 전부 수정 부탁드립니다**

<img width="812" alt="image" src="https://github.com/user-attachments/assets/96364229-83a7-4d62-ad2a-8f91f3f848b1" />
<img width="847" alt="image" src="https://github.com/user-attachments/assets/0b776a54-c630-4b84-9581-6924c30c222c" />

🙋‍♂️ 담당자
---
- 프론트엔드: @thswogh

**Comment by thswogh** [comment]
alert창 toast창으로 수정하였습니다
<img width="373" alt="image" src="https://github.com/user-attachments/assets/cf331a63-7a6c-48a4-8e16-e57a73ad6fef" />

**Comment by Cassiiopeia** [comment]
![image](https://github.com/user-attachments/assets/96bd8c5e-c03a-47f1-8080-28bdf1a79e34)

더 명확한 오류 반환가능한가요??

본일글은 답변하실 수 없습니다 같은 문구면 좋겠습니다

![image](https://github.com/user-attachments/assets/e01cff28-633c-44f6-b47e-8f2236b5dd80)

**Comment by Cassiiopeia** [comment]
#365  답변하기 버튼이 애초에 뜨면 안되는 해당 이슈 관련 프론트 이슈 연동시켜놓겠습니다

**Comment by thswogh** [comment]
@Cassiiopeia  서버에서 전송해주는 에러 메시지 나오게끔 수정했습니다
<img width="373" alt="image" src="https://github.com/user-attachments/assets/638ca837-2212-45be-8544-c79720b1c300" />

**Comment by thswogh** [comment]
에러메시지 프론트에서 가공해서 보여주는걸로 수정 필요
