### ISSUE TITLE
🔧 [기능개선][카테고리] 자료게시판 수강년도 페이지 정렬 수정 

### ISSUE THREAD

**Issue by seonglim** [Sejong-Balsamic/Malsami-FE#383]
🗒️ 설명
<img width="280" alt="스크린샷 2024-12-21 오후 7 07 27" src="https://github.com/user-attachments/assets/e8ea3fd4-4131-4c10-8d48-6db22b505fb8" />
<img width="278" alt="스크린샷 2024-12-21 오후 7 07 31" src="https://github.com/user-attachments/assets/f949ce5b-36c4-4bec-8c31-42f7ecb631d8" />

좌측 정렬되어있던 숫자를 중앙 정렬로 수정 부탁드립니다.

🙋‍♂️ 담당자
---
- 백엔드: 이름
- 프론트엔드: @thswogh 
- 디자인: @seonglim

**Comment by thswogh** [comment]
수정했습니다
<img width="634" alt="image" src="https://github.com/user-attachments/assets/cd313eec-e196-4655-b3db-d1fe25c6bc24" />

**Comment by thswogh** [comment]
@seonglim 
확인부탁드립니다 보고 이슈 닫아주세요!
