### ISSUE TITLE
⚙️ [기능추가][교과목명] 교과목명 서버에서 불러오기

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-FE#388]
🗒️ 설명
---
- 기존에는 프론트에서 "교과목명"들이 하드코딩 되어있습니다.
- "교과목명"들을 서버에서 불러오는 방식으로 수정해봅시다
- 서버에서 불러와서 저장하는 방식은 고민해보겠습니다

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
@thswogh  수정했습니다 확인부탁드립니다

**Comment by Cassiiopeia** [comment]
@thswogh 

프론트서버가 기동될떄

/api/sejong/subject/get-all

해당 API 를 호출하여

응답값의 subjects 배열의 모든 값을

기존의 프론트 텍스트파일 혹은 리액트 내부에 저장을 합니다
json 파일이던 txt파일이던 아니면 프론트측에서 DB를 사용할수도있는데 이런 DB사용도 고려해볼수있습니다.

일단 프론트 서버가 올라간후로 자주바뀌는내용은 아니라서 업데이트는 따로 고민할필요는없을것같고

바로바로 한글자한글자 검색하면 나와야하므로 성능고려 검색성능 고려 해야할것같습니다
